stages:
  - build
  - test

before_script:
  - apt-get -y update
  - apt-get -y upgrade
  - apt-get -y install golang-go
  - apt-get -y install python3 python3-pip python3-venv  # Install Python3, pip3, and python3-venv

build:
  stage: build   
  script:
    - go install github.com/tomnomnom/waybackurls@latest
    - go install github.com/hahwul/dalfox/v2@latest
    - go install github.com/KathanP19/Gxss@latest
    - export PATH=$HOME/go/bin:$PATH
    - go env GOPATH
    - cp /root/go/bin/Gxss /usr/local/bin
    - cp /root/go/bin/dalfox /usr/local/bin
    - cp /root/go/bin/waybackurls /usr/local/bin
    - waybackurls --help

    - python3 -m venv venv
    - source venv/bin/activate

    - python --version

    - pip3 install -r requirements.txt
    - python paramspider.py --domain att.com | Gxss -c 100 -p Xss 
#    - echo "testphp.vulnweb.com" | waybackurls  | Gxss -c 100 -p Xss | sort -u 
#    - echo https://us.trip.com | waybackurls | while read url ; do dalfox url $url  ; done
#    - echo https://us.trip.com | waybackurls | while read url ; do python3 xsstrike.py -u $url --crawl -l 4 ; done



    # Other build steps go here...

    - deactivate
  # artifacts:
  #   paths:
  #     - result.txt

