name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update system
      run: |
        sudo apt-get -y update
        sudo apt-get -y upgrade

    - name: Install dependencies
      run: |
        sudo apt-get -y install golang-go
        sudo apt-get -y install python3 python3-pip python3-venv

    - name: Build and Install dalfox
      run: |
        go install github.com/hahwul/dalfox/v2@latest
        go env GOPATH
       
