name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update system
      run: |
        sudo apt-get -y update
        sudo apt-get -y upgrade

    - name: Install dependencies
      run: |
        sudo apt-get -y install golang-go
        sudo apt-get -y install python3 python3-pip python3-venv

    - name: Build and Install dalfox
      run: |
        go install github.com/hahwul/dalfox/v2@latest
        sudo cp /home/runner/go/bin/dalfox /usr/local/bin

    - name: Build and Install Gxss
      run: |
        go install github.com/KathanP19/Gxss@latest
        sudo cp /home/runner/go/bin/Gxss /usr/local/bin

    - name: Setup Python Virtual Environment
      run: |
        python3 -m venv venv
        source venv/bin/activate

    - name: Install Python dependencies
      run: |
        pip3 install -r ./requirements.txt

    - name: Run paramspider and Gxss
      run: |
        python paramspider.py --domain decade.fr | Gxss -c 100 -p Xss
        

    - name: Deactivate Python Virtual Environment
      run: |
        deactivate
